### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by andersfalt** [olololoe110399/bedtime_stories#4]
I am getting several issues after following the steps indicated in the README file. Please se attached image.
![Skärmavbild 2023-12-28 kl  08 13 58](https://github.com/olololoe110399/bedtime_stories/assets/75035767/869f3990-205a-435d-b3e5-6f2a7a72bf3f)

**Comment by andersfalt** [comment]
I get the following error when trying to build the app.

lib/core/src/navigation/app_routes.gr.dart:115:5: Error: Type 'Key' not found.
    Key? key,
    ^^^
lib/core/src/navigation/app_routes.gr.dart:139:9: Error: Type 'Key' not found.
  final Key? key;
        ^^^
lib/presentation/src/app.dart:74:13: Error: Undefined name 'S'.
            S.delegate,
            ^
lib/presentation/src/app.dart:72:29: Error: The getter 'S' isn't defined for the class '_MyAppState'.
 - '_MyAppState' is from 'package:bedtime_stories/presentation/src/app.dart' ('lib/presentation/src/app.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'S'.
          supportedLocales: S.delegate.supportedLocales,
                            ^
lib/core/src/navigation/app_routes.gr.dart:21:22: Error: Couldn't find constructor 'DefineStoryPage'.
        child: const DefineStoryPage(),
                     ^^^^^^^^^^^^^^^
lib/core/src/navigation/app_routes.gr.dart:27:22: Error: Couldn't find constructor 'HistoryPage'.
        child: const HistoryPage(),
                     ^^^^^^^^^^^
lib/core/src/navigation/app_routes.gr.dart:33:22: Error: Couldn't find constructor 'JailbreakPage'.
        child: const JailbreakPage(),
                     ^^^^^^^^^^^^^
lib/core/src/navigation/app_routes.gr.dart:39:22: Error: Couldn't find constructor 'StartPage'.
        child: const StartPage(),
                     ^^^^^^^^^
lib/core/src/navigation/app_routes.gr.dart:46:16: Error: Method not found: 'StoryDetailPage'.
        child: StoryDetailPage(
               ^^^^^^^^^^^^^^^
lib/core/src/navigation/app_routes.gr.dart:115:5: Error: 'Key' isn't a type.
    Key? key,
    ^^^
lib/core/src/navigation/app_routes.gr.dart:139:9: Error: 'Key' isn't a type.
  final Key? key;
        ^^^
lib/core/src/hive/hive_database_manager.dart:35:26: Error: The method 'StoryHiveModelAdapter' isn't defined for the class 'HiveDatabaseManager'.
 - 'HiveDatabaseManager' is from 'package:bedtime_stories/core/src/hive/hive_database_manager.dart' ('lib/core/src/hive/hive_database_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'StoryHiveModelAdapter'.
    Hive.registerAdapter(StoryHiveModelAdapter());
                         ^^^^^^^^^^^^^^^^^^^^^
lib/presentation/src/story_detail/story_detail_page.dart:105:17: Error: No named parameter with the name 'endRadius'.
                endRadius: 90.0,
                ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/avatar_glow-3.0.1/lib/src/avatar_glow.dart:9:9: Context: Found this candidate, but the arguments don't match.
  const AvatarGlow({
        ^^^^^^^^^^
lib/data/src/data_sources/remote_data_source.dart:36:36: Error: The argument type 'String' can't be assigned to the parameter type 'List<OpenAIChatCompletionChoiceMessageContentItemModel>?'.
 - 'List' is from 'dart:core'.
 - 'OpenAIChatCompletionChoiceMessageContentItemModel' is from 'package:dart_openai/src/core/models/chat/sub_models/choices/sub_models/sub_models/content.dart' ('../../../.pub-cache/hosted/pub.dev/dart_openai-5.0.0/lib/src/core/models/chat/sub_models/choices/sub_models/sub_models/content.dart').
                content: e.content ?? "",
                                   ^
lib/data/src/repositories/openai_repository_impl.dart:59:67: Error: A value of type 'Object' can't be assigned to a variable of type 'String'.
 - 'Object' is from 'dart:core'.
        final String newStory = event.choices.first.delta.content ?? "";
                                                                  ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

**Comment by olololoe110399** [comment]
@andersfalt I fixed in new PR. You can git pull and run:
`make sync`
